### ISSUE TITLE
Target of URI doesn't exist: 'package:womensafteyhackfair/background_services.dart'

### ISSUE THREAD

**Issue by muhammadtalhasultan** [mhmzdev/Amaan-Women-Safety-App#1]
![Screenshot (343)](https://user-images.githubusercontent.com/31367048/149277665-b86b85ce-c095-402c-81db-84ce08e24d78.png)

**Comment by fenderstr82** [comment]
hello, did you find a solution?

**Comment by HassamTalha** [comment]
Hi, we were working on implementing the background services in a separate isolate. I have updated the project with the missing file being added to it. Thanks
