### ISSUE TITLE
Getting error 

### ISSUE THREAD

**Issue by mrbuddhu** [mhmzdev/Amaan-Women-Safety-App#2]
getting error : lib/Dashboard/DashWidgets/SafeHome.dart:176:31: Error: The getter 'simplePeriodicTask' isn't defined for the class '_SafeHomeState'.
 - '_SafeHomeState' is from 'package:womensafteyhackfair/Dashboard/DashWidgets/SafeHome.dart' ('lib/Dashboard/DashWidgets/SafeHome.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'simplePeriodicTask'.
                              simplePeriodicTask,
                              ^^^^^^^^^^^^^^^^^^

Please look into it :(

**Comment by HassamTalha** [comment]
Solved: It was just missing string quotes
